apiVersion: 'apps/v1beta1'
kind: 'StatefulSet'
metadata:
  name: 'webspoon-stateful-set'
spec:
  selector:
      matchLabels:
        # has to match .spec.template.metadata.labels
        app: 'webspoon-server'
  # reference back to the service name we created earlier on
  serviceName: 'webspoon-service'
  replicas: 2
  template:
    metadata:
      labels:
        # has to match .spec.selector.matchLabels
        app: 'webspoon-server' 
        version: 'v1'
        zone: 'dev'
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: 'webspoon'
        image: 'hiromuhota/webspoon:0.8.0.13-full'
        volumeMounts:
        # has to match name in volume claim templates
        - name: 'webspoon-persistent-volume-claim-kettle'
          mountPath: /root/.kettle
        # has to match name in volume claim templates
        - name: 'webspoon-persistent-volume-claim-pentaho'
          mountPath: /root/.pentaho
        env:
        - name: 'JAVA_OPTS'
          value: '-Xms1024m -Xmx1920m'
        ports:
        - containerPort: 8080
          protocol: 'TCP'
        resources:
          requests:
            cpu: '1'
            memory: '2Gi'
  volumeClaimTemplates:
  - metadata:
      name: 'webspoon-persistent-volume-claim-kettle'
    spec:
      accessModes: 
        - 'ReadWriteOnce'
      storageClassName: 'webspoon-storage-class'
      resources:
        requests:
          storage: '1Gi'
  - metadata:
      name: 'webspoon-persistent-volume-claim-pentaho'
    spec:
      accessModes: 
        - 'ReadWriteOnce'
      storageClassName: 'webspoon-storage-class'
      resources:
        requests:
          storage: '1Gi'